// src/react/Calendar.js
/* blurssism React · Calendar · © caffeinecat · MIT. 원본은 src/react/, scripts/build.mjs가 dist/index.mjs·index.cjs·bundle.js로 합칩니다. */
import { React, h, cx, useLocale } from "./_shared.js";
import { IconButton } from "./IconButton.js";


function sameDay(a, b) { return !!a && !!b && a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate(); }

function dayOf(d) { return d ? new Date(d.getFullYear(), d.getMonth(), d.getDate()) : null; }   // 시각을 버리고 날짜만

function addDays(d, n) { return new Date(d.getFullYear(), d.getMonth(), d.getDate() + n); }

/* 방향키 ±1일·±1주, Home·End 주의 처음·끝, PageUp·PageDown 이전·다음 달(Shift는 해). 고를 수 없는 날도 포커스는 갑니다. */
function calendarKey(e, d) {
  var k = e.key;
  if (k === "ArrowRight") return addDays(d, 1);
  if (k === "ArrowLeft") return addDays(d, -1);
  if (k === "ArrowDown") return addDays(d, 7);
  if (k === "ArrowUp") return addDays(d, -7);
  if (k === "Home") return addDays(d, -d.getDay());
  if (k === "End") return addDays(d, 6 - d.getDay());
  if (k === "PageUp" || k === "PageDown") {
    var dir = k === "PageUp" ? -1 : 1, y = d.getFullYear() + (e.shiftKey ? dir : 0), m = d.getMonth() + (e.shiftKey ? 0 : dir);
    return new Date(y, m, Math.min(d.getDate(), new Date(y, m + 1, 0).getDate()));
  }
  return null;
}

export function Calendar(p) {
  var L = useLocale(p.locale), DOW = L.dow;
  // 오늘은 마운트한 뒤에 정합니다. 서버(UTC)와 브라우저의 날짜가 달라 하이드레이션이 어긋나지 않게.
  var nowSt = React.useState(null), today = p.today || nowSt[0];
  React.useEffect(function () { if (!p.today) nowSt[1](new Date()); }, []);
  var init = p.value || p.today || new Date();
  var st = React.useState(new Date(init.getFullYear(), init.getMonth(), 1)), month = st[0], setMonth = st[1];
  var vKey = p.value ? p.value.getFullYear() * 12 + p.value.getMonth() : null;
  React.useEffect(function () { if (p.value) setMonth(new Date(p.value.getFullYear(), p.value.getMonth(), 1)); }, [vKey]);   // 바깥에서 값이 다른 달로 바뀌면 따라갑니다
  var act = React.useState(null), active = act[0], setActive = act[1], grid = React.useRef(null), wantFocus = React.useRef(false);
  var y = month.getFullYear(), m = month.getMonth(), lo = dayOf(p.min), hi = dayOf(p.max);
  var first = new Date(y, m, 1).getDay(), days = new Date(y, m + 1, 0).getDate(), cells = [];
  function inMonth(d) { return d && d.getFullYear() === y && d.getMonth() === m; }
  function off(d) { return (lo && d < lo) || (hi && d > hi); }
  var tab = inMonth(active) ? active : inMonth(p.value) ? dayOf(p.value) : inMonth(today) ? dayOf(today) : new Date(y, m, 1);
  React.useEffect(function () {
    if (!wantFocus.current || !grid.current) return;
    wantFocus.current = false;
    var b = grid.current.querySelector('[tabindex="0"]');
    if (b) b.focus();
  });
  function onKey(e) {
    var next = calendarKey(e, tab);
    if (!next) return;
    e.preventDefault();
    wantFocus.current = true;
    setActive(next);
    if (!inMonth(next)) setMonth(new Date(next.getFullYear(), next.getMonth(), 1));
  }
  for (var i = 0; i < first; i++) cells.push(h("span", { key: "b" + i }));
  for (var d = 1; d <= days; d++) (function (d) {
    var date = new Date(y, m, d), no = !!off(date);
    cells.push(h("button", { key: d, type: "button", className: "bl-cal-day", "aria-disabled": no ? "true" : undefined, tabIndex: sameDay(date, tab) ? 0 : -1,
      "aria-pressed": String(sameDay(date, p.value)), "data-today": String(sameDay(date, today)),
      "aria-label": L.dayLabel(y, m, d, DOW[date.getDay()]),
      onClick: function () { setActive(date); if (!no && p.onChange) p.onChange(date); } }, d));
  })(d);
  function go(n) { setActive(null); setMonth(new Date(y, m + n, 1)); }
  return h("div", { className: cx("bl-cal", p.className) },
    h("div", { className: "bl-cal-head" },
      h(IconButton, { icon: "chevron-left", label: L.prevMonth, plain: true, onClick: function () { go(-1); } }),
      h("p", { className: "bl-cal-title", "aria-live": "polite" }, L.monthTitle(y, m)),
      h(IconButton, { icon: "chevron-right", label: L.nextMonth, plain: true, onClick: function () { go(1); } })),
    h("div", { className: "bl-cal-grid", ref: grid, onKeyDown: onKey }, DOW.map(function (w, i) { return h("span", { key: i, className: "bl-cal-dow", "aria-hidden": "true" }, w); }), cells));
}

// svelte/Calendar.svelte
<script lang="ts">
  import { onMount, tick } from "svelte";
  import IconButton from "./IconButton.svelte";
  import { calendarKey, dayOf } from "./a11y.js";
  let { value = $bindable(), min, max, today, onchange, class: className }:
    { value?: Date; min?: Date; max?: Date; today?: Date; onchange?: (date: Date) => void; class?: string } = $props();
  const DOW = ["일", "월", "화", "수", "목", "금", "토"];
  // 오늘은 마운트한 뒤에 정합니다. 서버(UTC)와 브라우저의 날짜가 달라 하이드레이션이 어긋나지 않게.
  let now = $state<Date>();
  onMount(() => { now = new Date(); });
  const todayDate = $derived(today ?? now);
  // svelte-ignore state_referenced_locally — 처음 보여 줄 달만 정합니다
  const init = value ?? today ?? new Date();
  let month = $state(new Date(init.getFullYear(), init.getMonth(), 1));
  // 바깥에서 값이 다른 달로 바뀌면 따라갑니다
  const valueMonth = $derived(value ? value.getFullYear() * 12 + value.getMonth() : null);
  $effect(() => { if (valueMonth !== null && value) month = new Date(value.getFullYear(), value.getMonth(), 1); });
  let active = $state<Date>();
  let grid = $state<HTMLDivElement>();
  const y = $derived(month.getFullYear());
  const m = $derived(month.getMonth());
  const first = $derived(new Date(y, m, 1).getDay());
  const days = $derived(Array.from({ length: new Date(y, m + 1, 0).getDate() }, (_, i) => new Date(y, m, i + 1)));
  const lo = $derived(dayOf(min));
  const hi = $derived(dayOf(max));
  const same = (a?: Date, b?: Date) => !!a && !!b && a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
  const inMonth = (d?: Date) => !!d && d.getFullYear() === y && d.getMonth() === m;
  const off = (d: Date) => (!!lo && d < lo) || (!!hi && d > hi);
  const tab = $derived(inMonth(active) ? active! : inMonth(value) ? dayOf(value)! : inMonth(todayDate) ? dayOf(todayDate)! : new Date(y, m, 1));
  function pick(d: Date) { active = d; if (off(d)) return; value = d; onchange?.(d); }
  function go(n: number) { active = undefined; month = new Date(y, m + n, 1); }
  async function onkey(e: KeyboardEvent) {
    const next = calendarKey(e, tab);
    if (!next) return;
    e.preventDefault();
    active = next;
    if (!inMonth(next)) month = new Date(next.getFullYear(), next.getMonth(), 1);
    await tick();
    grid?.querySelector<HTMLElement>('[tabindex="0"]')?.focus();
  }
</script>

<div class={["bl-cal", className]}>
  <div class="bl-cal-head">
    <IconButton icon="chevron-left" label="이전 달" plain onclick={() => go(-1)} />
    <p class="bl-cal-title" aria-live="polite">{y}년 {m + 1}월</p>
    <IconButton icon="chevron-right" label="다음 달" plain onclick={() => go(1)} />
  </div>
  <!-- svelte-ignore a11y_no_static_element_interactions — 키 입력은 안쪽 날짜 버튼에서 올라온 것을 받습니다 -->
  <div class="bl-cal-grid" bind:this={grid} onkeydown={onkey}>
    {#each DOW as w (w)}<span class="bl-cal-dow" aria-hidden="true">{w}</span>{/each}
    {#each Array(first) as _, i (i)}<span></span>{/each}
    {#each days as d (d.getDate())}
      <button type="button" class="bl-cal-day" aria-disabled={off(d) ? "true" : undefined} tabindex={same(d, tab) ? 0 : -1}
        aria-pressed={same(d, value)} data-today={String(same(d, todayDate))}
        aria-label="{y}년 {m + 1}월 {d.getDate()}일 {DOW[d.getDay()]}요일" onclick={() => pick(d)}>{d.getDate()}</button>
    {/each}
  </div>
</div>
